[package]
edition = "2021"
name = "stm32-ptp"
version = "0.1.0"
license = "MIT OR Apache-2.0"

[dependencies]
embassy-stm32 = { version = "0.1.0", features = [
    "nightly",
    "defmt",
    "stm32f767zi",
    "memory-x",
    "unstable-pac",
    "time-driver-any",
    "exti",
] }
embassy-executor = { version = "0.3.0", features = [
    "nightly",
    "arch-cortex-m",
    "executor-thread",
    "defmt",
    "integrated-timers",
] }
embassy-time = { version = "0.1.3", features = [
    "defmt",
    "defmt-timestamp-uptime",
    "tick-hz-32_768",
] }

defmt = "0.3"
defmt-rtt = "0.4"
panic-probe = { version = "0.3", features = ["print-defmt"] }

cortex-m = { version = "0.7.6", features = [
    "inline-asm",
    "critical-section-single-core",
] }
cortex-m-rt = "0.7.0"

[patch.crates-io]
embassy-stm32 = { git = "https://github.com/embassy-rs/embassy.git", rev = "1133cbf90e469109e8b53daf7284742784e8fb33"}
embassy-time = { git = "https://github.com/embassy-rs/embassy.git", rev = "1133cbf90e469109e8b53daf7284742784e8fb33" }


[profile.release]
debug = 2
